### PR TITLE
UGENE-7848 Make parameters validation more user-friendly

### PR DESCRIPTION
**Pull request by DmitriiSukhomlinov**

### CODE REVIEW

**Review by yalgaer — COMMENTED** [review]
Could you please remove all new vanished from translations?

**Comment by DmitriiSukhomlinov** [comment]
> Could you please remove all new vanished from translations?

OK, anything else?

**Review by yalgaer — DISMISSED** [review]

**Review by yalgaer — COMMENTED** [review]
No other comments: don't add new vanished and I will approve

**Comment by DmitriiSukhomlinov** [comment]
Done, all tests passed in previous iteration, translations won't affect anything

**Review by yalgaer — APPROVED** [review]

**Pull request merged**
