### PR TITLE
UGENE-7475. Width of option panel for PCR Primer Design should not change width of all existing panels

### PR DESCRIPTION
**Pull request by evelinabis**
[7475](https://ugene.dev/tracker/browse/UGENE-7475). Tests passed.

### CODE REVIEW

**Review by smlnkcv — APPROVED** [review]

**Review by DmitriiSukhomlinov — CHANGES_REQUESTED** [review]
It work, but it's a very complicated fix of the very simple issue. You have no need of this complex calculations depends on an opened tab. The easiest way to fix this problem is just to decrease a minimum width of some widgets on the tab, look:
image
There are a lot of free space here which isn't in use at all. We could just remove it, and the general tab width will decrease.

**Comment by evelinabis** [comment]
> It work, but it's a very complicated fix of the very simple issue. You have no need of this complex calculations depends on an opened tab. The easiest way to fix this problem is just to decrease a minimum width of some widgets on the tab, look: image There are a lot of free space here which isn't in use at all. We could just remove it, and the general tab width will decrease.


History background:

1. In the beginning, [the task](https://ugene.dev/tracker/browse/UGENE-7321) was just to increase the width of the OP's tabs so that there was no scrolling (#417).
2. The tab was displayed differently on different screens and on some screens the width was not enough. The tab has been expanded even further (#444, [#586](https://github.com/ugeneunipro/ugene/pull/586/commits/e2a349982fb52ab5e14ccc1cd811019f075de349#diff-82398dda8c59051ac9a4c8cd05cf7198d4195aa74f99ad5337aa073519e053ec)).
3. This changed the behavior for [all tabs](https://github.com/ugeneunipro/ugene/pull/586#discussion_r721076307), so the changes [were reversed](https://github.com/ugeneunipro/ugene/pull/586/commits/80e2d98361d618928f4295a34fb3a3154158fe18#diff-82398dda8c59051ac9a4c8cd05cf7198d4195aa74f99ad5337aa073519e053ec). Scroll is back again.
4. Changes in [the PR](https://github.com/ugeneunipro/ugene/pull/601/commits/80e2d98361d618928f4295a34fb3a3154158fe18) were aimed at ensuring that
4.1. there was no scroll;
4.2. all widgets of the "PCR Primer Design" tab were displayed in full.
5. They [were rejected](https://github.com/ugeneunipro/ugene/pull/586/files/facf816765dcec5837bbe26e9cc99193cada40d2#r726800411) by yalgaer, so as part of the PR (#601) I decided not to do anything with tab width and created a new PR (#602) for this.
6. The PR (#602) was approved. Thus, our tab is wide, the others are not, there is no scrolling, while all the widgets are displayed.
7. The current PR is then in the process, which resolves [issue 7475](https://ugene.dev/tracker/browse/UGENE-7475).

The minimum value of the "Gibbs free energy" combobox is -999999999. Not all screens display this value in full. The Russian translation may have to be redone if I remove free space. Not everything you have highlighted affects the tab width. Most importantly, if I understand correctly, you recommend that I remove the free spacing and at the same time increase the width for all tabs.

Select the actions that I need to do, since I did not really understand what you want from me:

- [ ] Discard current changes. Affect [task 7475](https://ugene.dev/tracker/browse/UGENE-7475) only.
- [ ] Revert all changes related to the tab width and horizontal scrolling. Affects issues [7321](https://ugene.dev/tracker/browse/UGENE-7321) and [7475](https://ugene.dev/tracker/browse/UGENE-7475), remove changes in open PR (#619) in OptionsPanelWidget.h/cpp files.
- [ ] Increase the width for all tabs.
- [ ] Remove free space.

**Comment by evelinabis** [comment]
> > It work, but it's a very complicated fix of the very simple issue. You have no need of this complex calculations depends on an opened tab. The easiest way to fix this problem is just to decrease a minimum width of some widgets on the tab, look: image There are a lot of free space here which isn't in use at all. We could just remove it, and the general tab width will decrease.
> 
> History background:
> 
> 1. In the beginning, [the task](https://ugene.dev/tracker/browse/UGENE-7321) was just to increase the width of the OP's tabs so that there was no scrolling ([UGENE-7321. Increase width of option panel to make the tab fully visible. #417](https://github.com/ugeneunipro/ugene/pull/417)).
> 2. The tab was displayed differently on different screens and on some screens the width was not enough. The tab has been expanded even further ([UGENE-7321. Increase width of option panel to make the tab fully visible 1 #444](https://github.com/ugeneunipro/ugene/pull/444), [#586](https://github.com/ugeneunipro/ugene/pull/586/commits/e2a349982fb52ab5e14ccc1cd811019f075de349#diff-82398dda8c59051ac9a4c8cd05cf7198d4195aa74f99ad5337aa073519e053ec)).
> 3. This changed the behavior for [all tabs](https://github.com/ugeneunipro/ugene/pull/586#discussion_r721076307), so the changes [were reversed](https://github.com/ugeneunipro/ugene/pull/586/commits/80e2d98361d618928f4295a34fb3a3154158fe18#diff-82398dda8c59051ac9a4c8cd05cf7198d4195aa74f99ad5337aa073519e053ec). Scroll is back again.
> 4. Changes in [the PR](https://github.com/ugeneunipro/ugene/pull/601/commits/80e2d98361d618928f4295a34fb3a3154158fe18) were aimed at ensuring that
>    4.1. there was no scroll;
>    4.2. all widgets of the "PCR Primer Design" tab were displayed in full.
> 5. They [were rejected](https://github.com/ugeneunipro/ugene/pull/586/files/facf816765dcec5837bbe26e9cc99193cada40d2#r726800411) by yalgaer, so as part of the PR ([UGENE-7442. The reverse sequences in Task report [PCR Primer Design For DNA Assembly Task] should be taken from complementary sequence #601](https://github.com/ugeneunipro/ugene/pull/601)) I decided not to do anything with tab width and created a new PR ([UGENE-7321. Increase width of option panel to make the tab fully visible #602](https://github.com/ugeneunipro/ugene/pull/602)) for this.
> 6. The PR ([UGENE-7321. Increase width of option panel to make the tab fully visible #602](https://github.com/ugeneunipro/ugene/pull/602)) was approved. Thus, our tab is wide, the others are not, there is no scrolling, while all the widgets are displayed.
> 7. The current PR is then in the process, which resolves [issue 7475](https://ugene.dev/tracker/browse/UGENE-7475).
> 
> The minimum value of the "Gibbs free energy" combobox is -999999999. Not all screens display this value in full. The Russian translation may have to be redone if I remove free space. Not everything you have highlighted affects the tab width. Most importantly, if I understand correctly, you recommend that I remove the free spacing and at the same time increase the width for all tabs.
> 
> Select the actions that I need to do, since I did not really understand what you want from me:
> 
> * [ ]  Discard current changes. Affect [task 7475](https://ugene.dev/tracker/browse/UGENE-7475) only.
> * [ ]  Revert all changes related to the tab width and horizontal scrolling. Affects issues [7321](https://ugene.dev/tracker/browse/UGENE-7321) and [7475](https://ugene.dev/tracker/browse/UGENE-7475), remove changes in open PR ([Pcr primer design for dna assembly #619](https://github.com/ugeneunipro/ugene/pull/619)) in OptionsPanelWidget.h/cpp files.
> * [ ]  Increase the width for all tabs.
> * [x]  Remove free space.

@DmitriiSukhomlinov, please explain to me what needs to be done.

**Comment by evelinabis** [comment]
After talking with reviewer: "You just need to reduce the width of widgets on the tab".

**Comment by evelinabis** [comment]
This PR is no longer needed. See https://github.com/ugeneunipro/ugene/pull/619/commits/79ba48ec4a07b9d1c32856ce9e73376963d50875 #716.

**Pull request closed without merging**
