### PR TITLE
UGENE-7833 Set molecular weight units

### PR DESCRIPTION
**Pull request by DmitriiSukhomlinov**

### CODE REVIEW

**Comment by yalgaer** [comment]
Looks good will approve after tests

**Comment by DmitriiSukhomlinov** [comment]
@yalgaer wait for approve

**Comment by yalgaer** [comment]
> 

Did you run Windows GUI tests?

**Comment by DmitriiSukhomlinov** [comment]
> > 
> 
> Did you run Windows GUI tests?

I can run them, but they are **very** time consuming - 1-2 days to wait. I decided, its not required for such a minor fix

**Comment by yalgaer** [comment]
> > > 
> > 
> > 
> > Did you run Windows GUI tests?
> 
> I can run them, but they are **very** time consuming - 1-2 days to wait. I decided, its not required for such a minor fix

I see two runs for this PR, both of which are red. The last one has 12 failed tests.

**Comment by DmitriiSukhomlinov** [comment]
> > > > 
> > > 
> > > 
> > > Did you run Windows GUI tests?
> > 
> > 
> > I can run them, but they are **very** time consuming - 1-2 days to wait. I decided, its not required for such a minor fix
> 
> I see two runs for this PR, both of which are red. The last one has 12 failed tests.

I checked them - just 2 of them failed by reason, I fixed them. Other failures didn't have any real problem, it's just some test system instability. Lets pass them again, if you want

**Review by yalgaer — APPROVED** [review]

**Pull request merged**
