### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by serkan-maker**
Hello, I want to translate the application. Is there any translation file other than the files I added?

### CODE REVIEW

**Review by yalgaer — CHANGES_REQUESTED** [review]
Hi Serkan,
Thank you for this pull request. I think we can accept it once the percent of translated strings will be comparable with other languages we support (like Russian).

We have 57 files with translations today:  run `find . -name "russian.ts"` to see all of them. 
This PR now contains only 3.

**Comment by serkan-maker** [comment]
Hello, Yuliya. Yes, I found the files, I will continue to translate as I find time Thank you for the answer

**Review by yalgaer — CHANGES_REQUESTED** [review]
Hi Serkan,
I checked your PR.
All looks good but we need the following translations too:
U2Algorithm
U2Core
U2Formats
U2Gui
U2Lang
U2Private
U2View

**Comment by serkan-maker** [comment]
Hi, I Continue To Translate. I fixed the folder names
[ugene_tr.TR.tar.gz](https://github.com/ugeneunipro/ugene/files/6443406/ugene_tr.TR.tar.gz)

unfinished translations
Primer3
U2Core
umuscle
variants
workflow_designer
external_tool_support

**Comment by serkan-maker** [comment]
Hi, last 3 translation files left
translation rates
workflow_designer    24%
external_tool_support   19%
Primer3   35%
[ugene_tr.zip](https://github.com/ugeneunipro/ugene/files/6479564/ugene_tr.zip)

**Comment by serkan-maker** [comment]
Hi, last 2 translation files left
translation rates
workflow_designer 25%
external_tool_support 21%
[ugene_tr.zip](https://github.com/ugeneunipro/ugene/files/6489558/ugene_tr.zip)

**Comment by yalgaer** [comment]
> Hi, last 2 translation files left
> translation rates
> workflow_designer 25%
> external_tool_support 21%
> [ugene_tr.zip](https://github.com/ugeneunipro/ugene/files/6489558/ugene_tr.zip)

Nice! Please add a comment when you finished!

**Comment by serkan-maker** [comment]
Hi, last 1 translation files left
translation rates
external_tool_support 25%
[ugene_tr.zip](https://github.com/ugeneunipro/ugene/files/6515620/ugene_tr.zip)

**Comment by yalgaer** [comment]
Hi Sekan,
We will have feature freeze in 1 week. Please add whats left during this week, so we can include your changes into the next release.

**Comment by serkan-maker** [comment]
Hi Yuliya.
the final translation file is at 52% level.  i will try to finish

**Comment by serkan-maker** [comment]
Hi Yulia
translation completed
[ugene_tr.zip](https://github.com/ugeneunipro/ugene/files/6538361/ugene_tr.zip)

**Comment by yalgaer** [comment]
> Hi Yulia
> translation completed
> [ugene_tr.zip](https://github.com/ugeneunipro/ugene/files/6538361/ugene_tr.zip)

Thank you! I will take the latest attached ugene_tr.zip and will create a pull request with all needed code changes for it

**Comment by yalgaer** [comment]
Here is PR with the Turkish translations integrated:
https://github.com/ugeneunipro/ugene/pull/394

**Pull request closed without merging**
