### PR TITLE
UGENE-7845 Improve multiple selection in Sanger Reads Editor

### PR DESCRIPTION
**Pull request by DmitriiSukhomlinov**
No GUI test, cuz this changes are kinda visual and you just need to see it. Make a selection in Sanger reads editor to test.

### CODE REVIEW

**Review by yalgaer — COMMENTED** [review]
Could you please paste screenshots before/after for this UI-only change?

**Review by yalgaer — DISMISSED** [review]

**Comment by DmitriiSukhomlinov** [comment]
Selection frame (no selection frame before at all):

image

**Comment by DmitriiSukhomlinov** [comment]
Selection after:

image


Selection before:

image

**Comment by DmitriiSukhomlinov** [comment]
All tests passed except the flaky one

**Review by yalgaer — APPROVED** [review]

**Pull request merged**
