### PR TITLE
UGENE-7156 Replace the all macOS-define macros with Q_OS_DARWIN

### PR DESCRIPTION
**Pull request by DmitriiSukhomlinov**

### CODE REVIEW

**Review by yalgaer — COMMENTED** [review]
Looks good. Will approve after Nighly shows no issues.

BTW do you plan to run UGENE on iPad as a part of M1 support?

**Comment by DmitriiSukhomlinov** [comment]
> BTW do you plan to run UGENE on iPad as a part of M1 support?

I see what you mean. @atiunov and I decided, that it's better to use more general macro (`Q_OS_DARWIN`). Another option was `Q_OS_MAC`

**Review by evelinabis — APPROVED** [review]

**Comment by DmitriiSukhomlinov** [comment]
Test:
Precommit: [Windows](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/viewType.html?buildTypeId=UgeneCommitBuilds_CommitBuildWindows1064bitU64bit&branch_UgeneCommitBuilds=UGENE-7156&tab=buildTypeStatusDiv), [Linux](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/viewType.html?buildTypeId=UgeneCommitBuilds_CommitBuildUbuntu200464bitU64bit&branch_UgeneCommitBuilds=UGENE-7156&tab=buildTypeStatusDiv), [macOS](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/viewType.html?buildTypeId=UgeneCommitBuilds_CommitBuildMacOsX109564bitU64bit&branch_UgeneCommitBuilds=UGENE-7156&tab=buildTypeStatusDiv).
XML: [Windows](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/viewType.html?buildTypeId=bt117&branch_UgeneNightlyBuilds_XmlTests=UGENE-7156&tab=buildTypeStatusDiv), [Linux](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/viewLog.html?buildId=215812&tab=buildResultsDiv&buildTypeId=UgeneNightlyBuilds_XmlTests_NightlyBuildUbuntu200464bitLinux), [macOS](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/viewType.html?buildTypeId=UgeneNightlyBuilds_NightlyMacOsX1075macX64&branch_UgeneNightlyBuilds_XmlTests=UGENE-7156&tab=buildTypeStatusDiv).

There is a failed XML Linux text, but it's some unstable one.

@yalgaer do you need GUI?

**Comment by yalgaer** [comment]
Yes, GUI tests coverage is 10x more that the XML ones

**Comment by DmitriiSukhomlinov** [comment]
GUI: [Windows](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/viewType.html?buildTypeId=UgeneNightlyBuilds_GuiTests_GuiTestsSummaryWindows1032bit&branch_UgeneNightlyBuilds_GuiTests=UGENE-7156&tab=buildTypeStatusDiv), [Linux](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/viewType.html?buildTypeId=bt153&branch_UgeneNightlyBuilds_GuiTests=UGENE-7156&tab=buildTypeStatusDiv), [macOS](http://ugene-teamcity.unipro.ru:8111/ugene-teamcity/viewType.html?buildTypeId=UgeneNightlyBuilds_GuiTests_GuiTestsMacOsX10125Qt5macX64summary&branch_UgeneNightlyBuilds_GuiTests=UGENE-7156&tab=buildTypeStatusDiv)

2 tests failed, but they are unstable and fail from time to time

**Review by yalgaer — APPROVED** [review]

**Pull request merged**
