### PR TITLE
MSA Editor support for high DPI displays

### PR DESCRIPTION
**Pull request by ggrekhov**
Before:
before

After:
after

### CODE REVIEW

**Comment by dkandrov** [comment]
Thanks!

**Comment by epushkova** [comment]
As far as you are ex-teammate, I am proposing some refactoring: there should be a common widget that reacts on screen change and provides a proper size - so all the other text drawing widgets (SeqView, CircularView, Assembly, etc) can be inherited from it and don't bother about the screen.

**Comment by ggrekhov** [comment]
@epushkova, everything is simpler. See the pull request #23.

**Comment by ggrekhov** [comment]
I would consider another refactoring: extract a basic class for graphic widgets that have a cachedView. I added processing of devicePixelRatio() to these widgets but the basic class will simplify creating of new such widgets and remove copy/paste.

**Comment by epushkova** [comment]
Your suggestion and mine do not contradict.

**Comment by ggrekhov** [comment]
Yes, they don't, but there is no code for processing screen changes now

**Pull request merged**
